before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  github:
  prerelease: auto
dockers:
  -
    image_templates:
      - "ghcr.io/calyptia/go-repo-template/{{ .ProjectName }}:latest"
      - "ghcr.io/calyptia/go-repo-template/{{ .ProjectName }}:{{ .Major }}"
      - "ghcr.io/calyptia/go-repo-template/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/calyptia/go-repo-template/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"